### ISSUE TITLE
When I required theme.config.js IN tailwind.config.js, then failed to compile.

### ISSUE THREAD

**Issue by szluyufeng** [hawezo/tailwindcss-theming#10]
```
Failed to compile.

./app/javascript/stylesheets/application.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/src??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/stylesheets/application.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError

(2:2) `@apply` cannot be used with `.text-gray-600` because `.text-gray-600` either cannot be found, or its actual definition includes a pseudo-selector like :hover, :active, etc. If you're sure that `.text-gray-600` exists, make sure that any `@import` statements are being properly processed *before* Tailwind CSS sees your CSS, as `@apply` can only be used for classes in the same CSS tree.

  1 | body {
> 2 |   @apply font-sans text-sm leading-normal text-gray-600;
    |  ^
  3 | }
  4 | 
```

Everything is JUST the same as "https://github.com/hawezo/tailwindcss-theming/blob/master/docs/setup.md",
But it just failed.

So how can I get it work.

**Comment by szluyufeng** [comment]
PS: The Tailwindcss version is V1.20

**Comment by hawezo** [comment]
Hi @szluyufeng, as you can see in the error, this is a Tailwind issue - not an issue with this plugin. 

The reason it happens is because `tailwindcss-theming` actually replaces your whole color palette, for theming reasons (that's the goal of the plugin). Because of that, you no longer have the color `gray-600`, so the utility `.text-gray-600` no longer exist. 

So when you're trying to use Tailwind on your files, Tailwind will throw an error, which is perfectly expected. 

In order to fix this error, you need to replace your existing color utilities with the new ones you'll set up with `tailwindcss-theming` (see the documentation), and/or you can add back a `gray-600` color within this plugin too. Your choice. 

I hope my explaination is clear enough.

**Comment by szluyufeng** [comment]
Thanks hawezo, very very clear.
Can we choose to extend the color in 'theme.config.js' , not just replace the default color.

**Comment by hawezo** [comment]
Unfortunately not yet but this is something that I plan to do! See the other opened issue.

**Comment by szluyufeng** [comment]
@hawezo Looking forward for that. Thanks for your work!
