### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by muhajirdev** [hawezo/tailwindcss-theming#2]
Is there any example available?

**Comment by hawezo** [comment]
Hi, [there is a real-world example in the readme](https://github.com/hawezo/tailwindcss-theming#real-world-example). Is that what you're looking for? It's a good starter for every project.

**Comment by muhajirdev** [comment]
Ah, I was thinking something like this https://github.com/zeit/next.js/tree/master/examples/.

Where they have examples that we can run. We can see how it fits together.

Honestly, I think this plugin has a lot of API. Which is probably good as it gives a lot of flexibility. 
On the other hand. It's a bit overwhelming to "Get started" with this plugin.

That's why I think having a simple example project. Which the user can play around with, will help us to get started. 

Cool project btw :). Would love to see further development :)

**Comment by hawezo** [comment]
Oh, I see. Since it's using a a CSS framework, I did not setup anything to test with, but I can understand the need. 

Actually, I was waiting for [this issue](https://github.com/utkarshkukreti/tailwind.run/issues/5) to be resolved in order to add an example to play with. 

But you're right, I may add a simple Vue application or something to test if tailwind.run don't let me do this soon enough. 

Thanks for the kind words :)

**Comment by hawezo** [comment]
The documentation is clearer now. I will soon add some examples with `vue-cli` so you can clone and build them to try out the plugin.

**Comment by hawezo** [comment]
I added an example. See the [readme](https://github.com/hawezo/tailwindcss-theming/blob/master/docs/examples.md#application).
